=== DaniCardia/Codifica-di-testi/Esercizio6.dtd
<!ELEMENT TEI (teiHeader,text+)>
<!ELEMENT teiHeader (filedesc)>
<!ELEMENT filedesc (titleStmt,publicationStmt,sourceDesc)>
<!ELEMENT titleStmt (title+,respStmt)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT respStmt  (resp,name)>
<!ELEMENT resp (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT publicationStmt (publisher,date+,availability)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT availability (#PCDATA)>
<!ELEMENT sourceDesc (bibl)>
<!ELEMENT bibl (title+,author,publisher,date)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT text (body)>
<!ELEMENT body (div)>
<!ELEMENT div (p*)>
<!ELEMENT p (#PCDATA)>

<!ATTLIST TEI
    xmlns CDATA #REQUIRED
>

<!ATTLIST availability
    status CDATA #REQUIRED
>
<!ATTLIST div
    type CDATA #REQUIRED 
>

=== DaniCardia/Codifica-di-testi/Esercizio6.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE TEI SYSTEM "Esercizio6.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <filedesc>
            <titleStmt>
                <title>Noi, i ragazzi dello zoo di Berlino: edizione digitale</title>
                <respStmt>
                    <resp>Codifica di</resp>
                    <name>Daniela Cardia</name>
                </respStmt>
            </titleStmt>
            <publicationStmt>
                <publisher>Pisa</publisher>
                <date>04-06-2020</date>
                <availability status="free"></availability>
            </publicationStmt>    
            <sourceDesc><bibl>
                <title>Noi, i ragazzi dello zoo di Berlino</title>
                <author>Christiane Vera Felscherinow</author>
                <publisher>Biblioteca Universale Rizzoli - BUR</publisher>
                <date>Aprile 2004</date>
                </bibl></sourceDesc>
        </filedesc>
    </teiHeader>
    <text><body>
        <div type="book">
            <p>Era di un eccitante pazzesco. Mia madre fece bagagli, valigie e casse per giorni interi. Io capii che per noi sarebbe cominciata una nuova vita.</p>
            <p>Avevo compiuto sei anni e dopo il trasferimento sare dovuta andare a scuola. Mentre mia madre faceva senza sosta i bagali e diventava sempre più nervosa, io passavo tutto il giorno dai contadini Volkel. Aspettavo che le mucche entrassero nella stalla per la mungitura, davo da mangiare alle scrofe e ai polli e mi scatenavo con gli altri nel fieno, oppure portavo in giro i gattini. Era una splendida estate, la prima che ho vissuto con vera consapevolezza.</p>
            <p>Sapevo che presto saremmo andati lontano, in una grande cittù che si chiamava Berlino. La prima a partire con l'aereo fu mia madre, da sola. Voleva occuparsi dell'appartamento. Mia sorella piccola, io e mio padre arrivammo una settimana dopo. Per noi bambine era il primo viaggio in aereo. Tutto era immensamente emozionante.</p>
            <p>I miei genitore ci avevano raccontato storie meravigliose del gigantesco appartamento con sei grandi stanze nel quale avremmo abitato. E loro volevano guadagnaree molti soldi. Mia madre diceva che avremmo avuto una grande stanza tutta per noi. Volevano comprare bei mobili. Lei allora ci spiegò con tutti i particolari come sarebbe stata la nostra stanza. Questo lo ricordo ancora perché da bambina non ho mai smesso di immaginarmela, questa stanza. Man mano che crescevo diventava nella mia fantasia sempre più bella.</p>
            <p>E neanche ho dimenticato come era l'appartamento nel quale eravamo arrivati. Forse perché come prima cosa ne ebbi un orrore tremendo. Era così grande e vuoto che avevo paura di perdermi. Quando si parlava ad alta voce rimbombava terribilmente.</p>
            <p>Soltanto in tre stanze c'erano un paio di mobili. Nella stanza dei bambini c'erano due letti e un vecchio mobile da cucina con i nostri giochi. Nella seconda stanza c'era un letto per i miei genitori e nella stanza più grande un vecchio divano e un paio di sedie. Così vivevamo a Kreuzbeg, nella Paul-Lincke-Ufer.</p>
            <p>Dopo un paio di giorni mi fidai ad adnare da sola per strada con la bicicletta, dato che ci giocavano dei bambini che erano un po' più grandi di me. Al paese i più grandi avevano sempre giocato con i piccoli, e ci sorvegliavano anche. I bambini del nostro stabile mi dissero subito: <![CDATA[<<Cosa vuoi tu qui?>>]]>. Poi mi presero la bicicletta. Quando la riebbi indietro aveva una ruota a terra e un parafango piegato.</p>
            <p>Mio padre mi picchiò perché la bicicletta era rotta. Da allora andai in bicicletta solo per le nostre sei stanze.</p>
            <p>Tre stanze dovevano in realtà diventare l'ufficio. I miei genitori volevano aprire un'agenzia matrimoniale. Ma le scrivanie e le poltrone di cui parlavano non arrivarono mai. Il mobile da cucina rimase nella stanza dei bambini.</p>
            <p>Un giorno il sofà, i letti e l'armadio da cucina vennero caricati su un camioncino e portati in uno dei casermonidi Gropiusstadt. Li prendemmo un appartamento di due stanze e mezza all'undicesimo piano. E nella nostra mezza stanzetta dei bambini tutte le cose belle di cui mia madrea aveva parlato non ci sarebbero mai entrate.</p>
        </div>
        </body>
    </text>
</TEI>
